### PR TITLE
ROP microgadget tool

### PR DESCRIPTION
**Pull request by muzmu**
To run the micro-gadget tool use the following command for 32 bit binary:
./ROPgadget.py --binary [filename] --nojop --nosys --microgadgets --depth 3

For 64 bit binary,
./ROPgadget.py --binary [filename] --nojop --nosys --microgadgets --depth 5

### CODE REVIEW

**Comment by ianamason** [comment]
Hmmmm, why aren't I being notified about this pull request. I just noticed it because it was high up in the SRI-CSL list.  Have you been waiting long?

**Comment by muzmu** [comment]
Hello!

We are working with Dr.Ashish Gehani and have added an additional flag
--microgadget that outputs all the microgadgets that satisfies Turing
Completeness Classes. We have emailed him to inform you. And no we didn't
wait for long, as we just sent the pull request today. Thank you.

**Comment by ianamason** [comment]
This looks plausible. I need to try it out.  I think you need to futz with the setup.py too.

See this:

https://python-packaging.readthedocs.io/en/latest/non-code-files.html

Did you see this comment  @muzammilLUMS?
Without adding a manifest and making changes to the setup.py file, these changes will not work in a 
ROPgadget installed from an egg.

**Comment by ianamason** [comment]
Don't seem to be getting much feedback from @muzammilLUMS  

What is the "copy" binary there for?

**Comment by muzmu** [comment]
I am extremely sorry for the late reply. "copy" is just a binary file on which we tested our code. You can ignore it. We will integrate our code in setup.py in a day. Thank you for your feedback. Let us know if there is anything else need to be done @ianamason

**Comment by ianamason** [comment]
Actually @muzammilLUMS I have already merged the pull request, and am fixing it myself. So no need for you to do anything else. Thanks for your conttibutions!

**Comment by muzmu** [comment]
@ianamason I really appreciate your efforts. I have seen that you have tried to fix the installation part but --microgadgets flag is not working in the installed version. I am also working on the issue right now. Moreover, In "MANIFEST.in" file you have added the wrong "classes.txt" file. The one which is outside the "ropgadget" folder is the right one with both 32bit and 64bit classess .

**Comment by ianamason** [comment]
I didn't notice the duplication. OK. But the datafile  will need to be inside the ropgadet directory.
SO we should move it there. The resolution of the path assumes it will be there.

I just pushed another set of changes (resolving the path to the data file), it seems to work for me. Although I am not sure what I should be seeing.

Too many cooks spoil the broth, so if you want to take over for now, let me know.

**Comment by ianamason** [comment]
Also now that you are on board with the GitHub thing.  Why does the `--depth 3` mean 
32 bit and `--depth 5` mean 64 bit? That seems particularly obscure...

**Comment by ianamason** [comment]
@muzammilLUMS  (I added this to trigger email alerts) Note the two messages above.

**Comment by muzmu** [comment]
@ianamason The installed version seems to work only inside the "ROPgadget" directory, but not globally. The reason is  "ROPgadget" directory has its own "classes.txt" file. I did not realized earlier that the protocol of reading a ".txt" file is different for a program that need an installation procedure because every time the current directory is different,and conventional method read from the current directory. There are some changes that need to be made and I am happy to take over from here if there are no issues.

**Comment by ianamason** [comment]
Cool @muzammilLUMS . So  there are two classes.txt? 
Wow better change the name of yours then. 
I  will let you take over for now.

**Comment by muzmu** [comment]
@ianamason Our project was to analyze microgadgets. The size of microgadgets differs in 32 and 64 bits version. Basically, the 32 bit microgadget can contain maximum of 3 bytes and 64 bit microgadgets can contain upto 5 bytes due to different instruction sizes.

**Comment by ianamason** [comment]
Right @muzammilLUMS , that I guessed, but leaving it to the depth parameter is a bit odd.
maybe the microgadgets command could figure it out for itself?

**Comment by muzmu** [comment]
> Right @muzammilLUMS , that I guessed, but leaving it to the depth parameter is a bit odd.
> maybe the microgadgets command could figure it out for itself?

You are right and I have implemented that check in the microgadget command but with depth parameter ROP tool does not need to look for all size gadgets. Hence, it reduces the time of scan significantly. Without the depth parameter, the "microgadgets"  command will still work, but it will take much longer for large binaries.

**Comment by muzmu** [comment]
Initially we were working for 32 bits. The text file inside the "ropgadget" is only for 32 bits. The outer "class" caters both 32 and 64 bits that contains more than 6000 gadgets. So, the file inside the "ropgadget" is redundant and we can remove it. I was wondering should I send you another pull request with all the changes? Sorry for bothering you much @ianamason

**Comment by ianamason** [comment]
@muzammilLUMS  no problem. Sure fire away. I will merge quickly this time, so that we can strike while the iron is hot.

**Pull request merged**
