### PR TITLE
ROP microgadget tool

### PR DESCRIPTION
**Pull request by muzmu**
Hello! I have removed the duplicate files and fixed the absolute path issue. I have also added classes inside the data folder to make it more organized and added the file in the MANIFEST.in. We have made slight modifications. Now, the installed version is also working fine. Let us know if there are any questions/confusions.

To run the micro-gadget tool use the following command for 32 bit binary:
./ROPgadget.py --binary [filename] --nojop --nosys --microgadgets --depth 3

For 64 bit binary,
./ROPgadget.py --binary [filename] --nojop --nosys --microgadgets --depth 5

### CODE REVIEW

**Comment by muzmu** [comment]
@ianamason I have added the "classes.txt" file in the "data" folder inside "ropgadet" directory. You can remove all other "classes.txt" files.

**Comment by ianamason** [comment]
@muzammilLUMS  best that you clean up since you are doing the reorganization.

**Comment by abubakaraziz** [comment]
@ianamason Thanks for merging the files. We have cleaned up and reorganized all the files. No further action required. Regards

**Comment by ianamason** [comment]
Thanks @muzammilLUMS for your efforts.

**Pull request merged**
